#Requires -RunAsAdministrator
$ErrorActionPreference = "Stop"
$Root = Split-Path -Parent $MyInvocation.MyCommand.Path
Set-Location -LiteralPath $Root

$TaskName = "ChengziUserBehavior"
$Port = 3001

# Locate app dir by server file (avoid hardcoding Chinese path literals in this script)
$AppDir = Get-ChildItem -LiteralPath $Root -Directory -ErrorAction Stop |
    Where-Object { Test-Path -LiteralPath (Join-Path $_.FullName "server-with-db.js") } |
    Select-Object -First 1 -ExpandProperty FullName
if (-not $AppDir) {
    throw "server-with-db.js not found under project root. Expected under a child folder."
}

$NodeCandidates = @(
    "D:\Program Files\nodejs\node.exe",
    "C:\Program Files\nodejs\node.exe",
    "$env:LOCALAPPDATA\Programs\node\node.exe"
)
$cmdNode = Get-Command node -ErrorAction SilentlyContinue
if ($cmdNode) { $NodeCandidates += $cmdNode.Source }
$Node = $NodeCandidates | Where-Object { $_ -and (Test-Path -LiteralPath $_) } | Select-Object -First 1
if (-not $Node) {
    throw "node.exe not found. Install Node.js or add it to PATH, then rerun."
}

# Write absolute paths for SYSTEM (no user PATH). Do NOT put Chinese paths here.
$cfgPath = Join-Path $Root "service_config_user_behavior.bat"
$cfgLines = @(
    "@echo off",
    "REM generated by install_boot_service_user_behavior.ps1",
    ('set "DASHBOARD_NODE={0}"' -f $Node),
    ('set "DASHBOARD_PORT={0}"' -f $Port)
)
$enc = [System.Text.Encoding]::GetEncoding(0)
[System.IO.File]::WriteAllLines($cfgPath, $cfgLines, $enc)

$serviceBat = Join-Path $Root "start_user_behavior_service.bat"
if (-not (Test-Path -LiteralPath $serviceBat)) {
    throw "Missing start_user_behavior_service.bat"
}

New-Item -ItemType Directory -Force -Path (Join-Path $Root "logs") | Out-Null

Write-Host "[1/4] Grant SYSTEM access to project and Node..."
& icacls $Root /grant "SYSTEM:(OI)(CI)RX" /C /Q | Out-Null
& icacls $AppDir /grant "SYSTEM:(OI)(CI)RX" /T /C /Q | Out-Null
& icacls (Join-Path $Root "logs") /grant "SYSTEM:(OI)(CI)M" /T /C /Q | Out-Null
& icacls $Node /grant "SYSTEM:RX" /C /Q | Out-Null
$nodeDir = Split-Path $Node -Parent
& icacls $nodeDir /grant "SYSTEM:(OI)(CI)RX" /T /C /Q | Out-Null
$envFile = Join-Path $AppDir ".env"
if (Test-Path -LiteralPath $envFile) {
    & icacls $envFile /grant "SYSTEM:R" /C /Q | Out-Null
}

Write-Host "[2/4] Remove logon-only autostart / old task..."
$startupDir = Join-Path $env:APPDATA "Microsoft\Windows\Start Menu\Programs\Startup"
Get-ChildItem -LiteralPath $startupDir -Filter "*.lnk" -ErrorAction SilentlyContinue | ForEach-Object {
    try {
        $sh = New-Object -ComObject WScript.Shell
        $sc = $sh.CreateShortcut($_.FullName)
        if ($sc.TargetPath -like "*start_user_behavior*" -or $_.Name -like "*ChengziUserBehavior*") {
            Remove-Item -LiteralPath $_.FullName -Force
            Write-Host ("  removed " + $_.Name)
        }
    } catch {}
}
Unregister-ScheduledTask -TaskName $TaskName -Confirm:$false -ErrorAction SilentlyContinue

Write-Host "[3/4] Register boot scheduled task (SYSTEM, no login required)..."
$action = New-ScheduledTaskAction -Execute "cmd.exe" -Argument ("/c `"{0}`"" -f $serviceBat) -WorkingDirectory $Root
$trigger = New-ScheduledTaskTrigger -AtStartup
$trigger.Delay = "PT1M"
$principal = New-ScheduledTaskPrincipal -UserId "SYSTEM" -LogonType ServiceAccount -RunLevel Highest
$settings = New-ScheduledTaskSettingsSet `
    -AllowStartIfOnBatteries `
    -DontStopIfGoingOnBatteries `
    -StartWhenAvailable `
    -RestartCount 5 `
    -RestartInterval (New-TimeSpan -Minutes 1) `
    -ExecutionTimeLimit ([TimeSpan]::Zero) `
    -MultipleInstances IgnoreNew `
    -Priority 4

Register-ScheduledTask `
    -TaskName $TaskName `
    -Action $action `
    -Trigger $trigger `
    -Principal $principal `
    -Settings $settings `
    -Description "Chengzi user-behavior intranet service (boot, port 3001, no login)" `
    -Force | Out-Null

Write-Host ("[4/4] Ensure firewall allows port {0}..." -f $Port)
$fwName = "ChengziUserBehavior-$Port"
$existing = Get-NetFirewallRule -DisplayName $fwName -ErrorAction SilentlyContinue
if (-not $existing) {
    New-NetFirewallRule -DisplayName $fwName -Direction Inbound -Protocol TCP -LocalPort $Port -Action Allow | Out-Null
}

Write-Host "Starting task now..."
Get-NetTCPConnection -LocalPort $Port -State Listen -ErrorAction SilentlyContinue |
    ForEach-Object { Stop-Process -Id $_.OwningProcess -Force -ErrorAction SilentlyContinue }
Start-Sleep -Seconds 2
Start-ScheduledTask -TaskName $TaskName
Start-Sleep -Seconds 8

$ok = $false
try {
    $r = Invoke-WebRequest -Uri ("http://127.0.0.1:{0}/dashboard-db.html" -f $Port) -UseBasicParsing -TimeoutSec 10
    $ok = ($r.StatusCode -eq 200)
} catch {}

Write-Host ""
Write-Host "========================================"
Write-Host "  Installed: starts at boot (no login)"
Write-Host "========================================"
Write-Host ("Task:   {0}" -f $TaskName)
Write-Host ("App:    {0}" -f $AppDir)
Write-Host ("Node:   {0}" -f $Node)
Write-Host ("Local:  http://127.0.0.1:{0}/dashboard-db.html" -f $Port)
Get-NetIPAddress -AddressFamily IPv4 |
    Where-Object { $_.IPAddress -notlike "127.*" -and $_.PrefixOrigin -ne "WellKnown" } |
    ForEach-Object { Write-Host ("LAN:    http://{0}:{1}/dashboard-db.html" -f $_.IPAddress, $Port) }
Write-Host ("Log:    {0}\logs\user-behavior-service.log" -f $Root)
Write-Host "Remove: right-click uninstall_boot_service_user_behavior.bat -> Run as administrator"
if ($ok) {
    Write-Host "Status: running, HTTP 200 OK"
} else {
    Write-Host "Status: task registered; if no response, check the log"
}
Write-Host ""
